on: 
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
          
      - id: try_fetching_testing_release
        continue-on-error: true
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linuxTESTING_x86_64-latest.tar.gz
    
      - name: There are no TESTING releases, checking regular releases instead
        if: steps.try_fetching_testing_release.outcome == 'failure'
        run: |
          curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz

      - name: rename nightly tar
        run: mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz

      - name: decompress the tar
        run: tar -xzf roc_nightly.tar.gz

      - run: rm roc_nightly.tar.gz

      - name: simplify nightly folder name
        run: mv roc_nightly* roc_nightly

      - run: ./roc_nightly/roc version

      - run: sudo apt install -y expect ncat
      # expect for testing
      # ncat for tcp-client example

      - run: expect -v

      - run: bash ./platform/glue.sh

      # Run all tests 
      - run: ROC=./roc_nightly/roc EXAMPLES_DIR=./examples/ ./ci/all_tests.sh

# TODO clippy, rustfmt, roc fmt check

