on:
  pull_request:
  workflow_dispatch:

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-latest-release:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3

      - name: remove everything except some ci scripts
        run: |
          mkdir temp
          mv ./ci/test_latest_release.sh temp
          mv ./ci/get_latest_release_git_files.sh temp
          find . -mindepth 1 -maxdepth 1 ! -name 'temp' -exec rm -rf {} +

      - name: Get all git files of the latest basic-cli release
        run: ./temp/get_latest_release_git_files.sh

      - name: Use ./ci/test_latest_release.sh of the latest git main
        run: mv -f ./temp/test_latest_release.sh ./ci/

      # temp issue with new string interpolation syntax
      # TODO undo when 0.7.2 or 0.8.0 is released
      - run: rm examples/tcp-client.roc
      
      - name: Run all tests with latest roc release + latest basic-cli release
        run: EXAMPLES_DIR=./examples/ ./ci/test_latest_release.sh
